version: '3'

services:
  stock-reader:
    image: stock-reader
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: stock-reader
    command: >-
      --spring.profiles.active=insecureHttpClient
      --api.token=token_here
      --api.url=https://sandbox.iexapis.com/stable/
    environment:
      - ENVIRONMENT=local-docker
      - APPLICATION=stock_reader
      - APP_VERSION=latest
      - COMPONENT=jar_file