version: '3'

services:
  stock-api-consumer:
    image: stock-api-consumer
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: stock-api-consumer
    command: >-
      --spring.profiles.active=insecureHttpClient
      --api.token=Tpk_dbb40ba6fe374ef8bc4ea217cfd37639
      --api.url=https://sandbox.iexapis.com/stable/
      --database.name=stock_database
      --database.user=dummy_user
      --database.password=password
      --database.endpoint=mysqldatabase
      --database.port=3306
    environment:
      - ENVIRONMENT=local-docker
      - APPLICATION=stock-api-consumer
      - APP_VERSION=latest
      - COMPONENT=jar_file
    depends_on:
      - prometheus
      - mysqldatabase

  mysqldatabase:
    image: mysql:5.7
    ports:
      - "3306:3306"
#    command: --init-file /data/application/init.sql
#    volumes:
#      - ./init.sql:/data/application/init.sql
    restart: always
    container_name: mysqldatabase
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "stock_database"
      MYSQL_USER: "dummy_user"
      MYSQL_PASSWORD: "password"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - "prometheus"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
    env_file:
      - ./grafana/config.monitoring
    restart: always
