version: '3'

services:
  stock-api-consumer:
    image: stock-api-consumer
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: stock-api-consumer
    command: >-
      --spring.profiles.active=insecureHttpClient
      --api.token=token_here
      --api.url=https://sandbox.iexapis.com/stable/
    environment:
      - ENVIRONMENT=local-docker
      - APPLICATION=stock-api-consumer
      - APP_VERSION=latest
      - COMPONENT=jar_file
    depends_on:
      - "prometheus"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - "prometheus"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
    env_file:
      - ./grafana/config.monitoring
    restart: always
