version: '3'

services:
  stock-reader:
    image: stock-reader
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: stock-reader
    command: >-
      --spring.profiles.active=apiTokenProvider,apiUrlProvider,insecureHttpClient
      --api.token.sandbox=token
      --api.url.sandbox=https://sandbox.url.com/
      --sandbox.enabled=TRUE
    environment:
      - ENVIRONMENT=local-docker
      - APPLICATION=stock_reader
      - APP_VERSION=latest
      - COMPONENT=jar_file